#!/bin/bash
# Set up local development environment for BuildTrace

set -e

# Configuration
PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project)}"
REGION="${REGION:-us-west2}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=========================================="
echo "BuildTrace Local Development Setup"
echo "Project: $PROJECT_ID"
echo "=========================================="
echo ""

# Check prerequisites
if ! command -v gcloud &> /dev/null; then
    echo "❌ Error: gcloud CLI not found. Please install it first."
    exit 1
fi

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: PROJECT_ID not set. Please set it:"
    echo "  export PROJECT_ID='your-project-id'"
    exit 1
fi

# Get Cloud SQL connection name
echo "Getting Cloud SQL connection details..."
DB_CONNECTION_NAME=$(gcloud sql instances describe buildtrace-dev-db \
  --format="value(connectionName)" 2>/dev/null || echo "")

if [ -z "$DB_CONNECTION_NAME" ]; then
    echo "⚠️  Warning: Cloud SQL instance not found. You may need to create it first."
    DB_CONNECTION_NAME="$PROJECT_ID:$REGION:buildtrace-dev-db"
fi

# Create .env.local from template
echo "Creating .env.local file..."
if [ -f "$PROJECT_ROOT/.env.local" ]; then
    echo "⚠️  .env.local already exists. Backing up to .env.local.backup"
    cp "$PROJECT_ROOT/.env.local" "$PROJECT_ROOT/.env.local.backup"
fi

# Get database password from Secret Manager
echo "Retrieving database password from Secret Manager..."
DB_PASSWORD=$(gcloud secrets versions access latest --secret="db-user-password" 2>/dev/null || echo "CHANGE_ME")

# Get OpenAI API key from Secret Manager
echo "Retrieving OpenAI API key from Secret Manager..."
OPENAI_KEY=$(gcloud secrets versions access latest --secret="openai-api-key" 2>/dev/null || echo "CHANGE_ME")

# Create .env.local
cat > "$PROJECT_ROOT/.env.local" << EOF
# BuildTrace Local Development Environment
# Generated by setup-local.sh
# Update values as needed

# GCP Configuration
PROJECT_ID=$PROJECT_ID
REGION=$REGION
ZONE=${REGION}-a

# Database Configuration
DB_CONNECTION_NAME=$DB_CONNECTION_NAME
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=buildtrace_db
DB_USER=buildtrace_user
DB_PASSWORD=$DB_PASSWORD

# Cloud Storage
INPUT_BUCKET=buildtrace-dev-input-$PROJECT_ID
PROCESSED_BUCKET=buildtrace-dev-processed-$PROJECT_ID
ARTIFACTS_BUCKET=buildtrace-dev-artifacts-$PROJECT_ID

# Pub/Sub
PUBSUB_OCR_TOPIC=buildtrace-dev-ocr-queue
PUBSUB_DIFF_TOPIC=buildtrace-dev-diff-queue
PUBSUB_SUMMARY_TOPIC=buildtrace-dev-summary-queue
PUBSUB_ORCHESTRATOR_TOPIC=buildtrace-dev-orchestrator-queue

# OpenAI
OPENAI_API_KEY=$OPENAI_KEY
OPENAI_MODEL=gpt-4o

# Authentication
GOOGLE_APPLICATION_CREDENTIALS=./buildtrace-key.json

# Application
ENVIRONMENT=development
DEBUG=True
LOG_LEVEL=DEBUG
SECRET_KEY=$(openssl rand -hex 32)

# Flask
FLASK_APP=app.py
FLASK_ENV=development
EOF

echo "✅ Created .env.local"

# Check if service account key exists
if [ ! -f "$PROJECT_ROOT/buildtrace-key.json" ]; then
    echo ""
    echo "Service account key not found. Would you like to download it? (y/n)"
    read -p "> " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Downloading service account key..."
        gcloud iam service-accounts keys create "$PROJECT_ROOT/buildtrace-key.json" \
          --iam-account=buildtrace-service-account@$PROJECT_ID.iam.gserviceaccount.com
        
        # Add to .gitignore if not already there
        if ! grep -q "buildtrace-key.json" "$PROJECT_ROOT/.gitignore" 2>/dev/null; then
            echo "buildtrace-key.json" >> "$PROJECT_ROOT/.gitignore"
            echo "*.json" >> "$PROJECT_ROOT/.gitignore"
        fi
        
        echo "✅ Service account key downloaded"
    else
        echo "⚠️  You'll need to download the service account key manually:"
        echo "  gcloud iam service-accounts keys create buildtrace-key.json \\"
        echo "    --iam-account=buildtrace-service-account@$PROJECT_ID.iam.gserviceaccount.com"
    fi
else
    echo "✅ Service account key already exists"
fi

# Create local-db-setup.sh script
echo ""
echo "Creating local database setup script..."
cat > "$SCRIPT_DIR/local-db-setup.sh" << 'SCRIPT'
#!/bin/bash
# Start Cloud SQL Proxy for local development

set -e

PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project)}"
REGION="${REGION:-us-west2}"

if [ -z "$PROJECT_ID" ]; then
    echo "Error: PROJECT_ID not set"
    exit 1
fi

DB_CONNECTION_NAME="$PROJECT_ID:$REGION:buildtrace-dev-db"

echo "Starting Cloud SQL Proxy..."
echo "Connection: $DB_CONNECTION_NAME"
echo "Local port: 5432"
echo ""
echo "Press Ctrl+C to stop"
echo ""

cloud_sql_proxy -instances=$DB_CONNECTION_NAME=tcp:5432
SCRIPT

chmod +x "$SCRIPT_DIR/local-db-setup.sh"
echo "✅ Created local-db-setup.sh"

# Summary
echo ""
echo "=========================================="
echo "✅ Local Development Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Review and update .env.local with your values"
echo "  2. Start Cloud SQL Proxy (in separate terminal):"
echo "     ./scripts/dev-setup/local-db-setup.sh"
echo "  3. Install Python dependencies:"
echo "     pip install -r requirements.txt"
echo "  4. Run the application:"
echo "     python app.py"
echo ""
echo "Files created:"
echo "  - .env.local (environment variables)"
echo "  - scripts/dev-setup/local-db-setup.sh (database proxy script)"
echo ""

