#!/bin/bash

# OAuth Flow End-to-End Test Script
# This script provides instructions and verification steps for manual testing

PROJECT_ID="buildtrace-dev"
FRONTEND_URL="https://buildtrace-frontend-136394139608.us-west2.run.app"
BACKEND_URL="https://buildtrace-backend-136394139608.us-west2.run.app"

echo "═══════════════════════════════════════════════════════"
echo "OAuth Flow - Manual Test Instructions"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Frontend URL: $FRONTEND_URL"
echo "Backend URL:  $BACKEND_URL"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "TEST CASE 1: Fresh Login from Landing Page"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "SETUP:"
echo "1. Open browser DevTools (F12)"
echo "2. Go to Application > Local Storage"
echo "3. Delete all 'buildtrace-*' keys (token, user)"
echo "4. Go to Console tab (keep it open)"
echo ""
echo "STEPS:"
echo "1. Navigate to: $FRONTEND_URL"
echo "2. You should see login page (if not, it's a bug)"
echo "3. Click 'Sign in with Google'"
echo "4. Complete Google OAuth (use dev@buildtraceai.com)"
echo ""
echo "EXPECTED RESULT:"
echo "✓ Browser should land on: $FRONTEND_URL/"
echo "✓ Upload/comparison page should be visible"
echo "✓ Console should show:"
echo "   [OAuth] Callback received: ..."
echo "   [OAuth] Token stored in Zustand store"
echo "   [OAuth] Token in localStorage: YES (...)"
echo "   [OAuth] Setting user in store: ..."
echo "   [OAuth] User authentication complete - state updated"
echo "   [OAuth] URL cleaned. Zustand will trigger re-render."
echo "   [Home] Already authenticated: ..."
echo "   [Home] Rendering UploadPage for authenticated user"
echo ""
echo "✗ FAIL CONDITIONS:"
echo "   - Redirects to /login after OAuth"
echo "   - Shows loading spinner forever"
echo "   - Console shows errors"
echo ""
read -p "Press Enter when ready to check logs..."

echo ""
echo "═══════════════════════════════════════════════════════"
echo "Checking backend logs for last OAuth callback..."
echo "═══════════════════════════════════════════════════════"
gcloud logging read "resource.type=cloud_run_revision AND resource.labels.service_name=buildtrace-backend AND textPayload:\"Redirecting to frontend\"" \
  --limit=1 \
  --format="table(timestamp,textPayload)" \
  --project=$PROJECT_ID \
  --freshness=5m

echo ""
echo "═══════════════════════════════════════════════════════"
echo "Checking frontend logs..."
echo "═══════════════════════════════════════════════════════"
gcloud logging read "resource.type=cloud_run_revision AND resource.labels.service_name=buildtrace-frontend" \
  --limit=10 \
  --format="table(timestamp,textPayload)" \
  --project=$PROJECT_ID \
  --freshness=5m

echo ""
echo "═══════════════════════════════════════════════════════"
echo "TEST CASE 2: Already Authenticated User"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "STEPS:"
echo "1. Keep the same browser window (don't clear localStorage)"
echo "2. Navigate to: $FRONTEND_URL"
echo ""
echo "EXPECTED RESULT:"
echo "✓ Upload/comparison page loads immediately"
echo "✓ No redirect to /login"
echo "✓ Console shows:"
echo "   [Home] Already authenticated: ..."
echo ""
read -p "Press Enter when tested..."

echo ""
echo "═══════════════════════════════════════════════════════"
echo "TEST CASE 3: Token Expired (Simulated)"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "SETUP:"
echo "1. In DevTools > Application > Local Storage"
echo "2. Find 'buildtrace-token' key"
echo "3. Change the value to 'invalid_token_xyz'"
echo ""
echo "STEPS:"
echo "1. Navigate to: $FRONTEND_URL"
echo ""
echo "EXPECTED RESULT:"
echo "✓ Redirects to /login"
echo "✓ Token cleared from localStorage"
echo "✓ Console shows:"
echo "   [Home] Authentication failed - redirecting to login"
echo ""
read -p "Press Enter when tested..."

echo ""
echo "═══════════════════════════════════════════════════════"
echo "TEST CASE 4: Direct Access to Login Page When Authenticated"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "SETUP:"
echo "1. Complete Test Case 1 first (be authenticated)"
echo ""
echo "STEPS:"
echo "1. Navigate to: $FRONTEND_URL/login"
echo ""
echo "EXPECTED RESULT:"
echo "✓ Immediate redirect to /"
echo "✓ Upload/comparison page visible"
echo ""
read -p "Press Enter when tested..."

echo ""
echo "═══════════════════════════════════════════════════════"
echo "VERIFICATION CHECKLIST"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Check these in browser DevTools after Test Case 1:"
echo ""
echo "□ localStorage has 'buildtrace-token'"
echo "□ localStorage has 'buildtrace-user'"
echo "□ Console shows all [OAuth] log messages"
echo "□ Console shows [Home] Rendering UploadPage"
echo "□ No errors in Console"
echo "□ Network tab shows /api/v1/auth/me call with Authorization header"
echo "□ Network tab shows /api/v1/auth/me returns 200 (not 401)"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "Test Complete!"
echo "═══════════════════════════════════════════════════════"

