steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrace-repo/buildtrace-overlay:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrace-repo/buildtrace-overlay:$COMMIT_SHA']

  # Deploy web app to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'buildtrace-overlay'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrace-repo/buildtrace-overlay:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--add-cloudsql-instances'
      - 'buildtrace:us-central1:buildtrace-postgres'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,INSTANCE_CONNECTION_NAME=buildtrace:us-central1:buildtrace-postgres,DB_USER=buildtrace_user,DB_NAME=buildtrace_db,GCS_BUCKET_NAME=buildtrace-storage,DB_PASS=iOYQKGXMasXmV+2qKWEHC0BDxdgFOOltg/PUm70vfVI=,OPENAI_API_KEY=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'

  # Deploy background job processor to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'buildtrace-job-processor'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrace-repo/buildtrace-overlay:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '32Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '1'
      - '--add-cloudsql-instances'
      - 'buildtrace:us-central1:buildtrace-postgres'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,INSTANCE_CONNECTION_NAME=buildtrace:us-central1:buildtrace-postgres,DB_USER=buildtrace_user,DB_NAME=buildtrace_db,GCS_BUCKET_NAME=buildtrace-storage,DB_PASS=iOYQKGXMasXmV+2qKWEHC0BDxdgFOOltg/PUm70vfVI=,OPENAI_API_KEY=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'
      - '--command'
      - 'python,gcp/infrastructure/job_processor.py'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrace-repo/buildtrace-overlay:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s